name: Release
on:
  release:
    types: [published]
jobs:
  build_free2ki:
    name: Build free2ki FreeCAD Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          submodules: recursive
      - uses: astral-sh/setup-uv@v5
      - uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - name: Build FreeCAD Package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          NAME="free2ki_$(sed "s/-/_/;s/\./-/g" <<< $GITHUB_REF_NAME).zip"
          python .github/workflows/build_freecad_package.py --extra-files icons/
          sha256sum $NAME | cut -c -64 | tr -d "\n" > $NAME.sha256
          gh release upload $GITHUB_REF_NAME $NAME
          gh release upload $GITHUB_REF_NAME $NAME.sha256
