name: Release
on:
  release:
    types: [published]
jobs:
  build_free2ki:
    name: Build free2ki FreeCAD Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Build FreeCAD Package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install requests
          NAME="free2ki_$(sed "s/-/_/;s/\./-/g" <<< $GITHUB_REF_NAME).zip"
          python .github/workflows/build_freecad_package.py \
            --extra-files icons/kicad.png icons/material.png
          sha256sum $NAME | cut -c -64 | tr -d "\n" > $NAME.sha256
          gh release upload $GITHUB_REF_NAME $NAME
          gh release upload $GITHUB_REF_NAME $NAME.sha256
